
// This file has been generated by the GUI designer. Do not modify.
namespace AutoID_pipeline
{
	public partial class InfoWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label objName;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label3;

		private global::Gtk.Label semInfo;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AutoID_pipeline.InfoWindow
			this.Name = "AutoID_pipeline.InfoWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("InfoWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child AutoID_pipeline.InfoWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.objName = new global::Gtk.Label();
			this.objName.Name = "objName";
			this.objName.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.vbox1.Add(this.objName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.objName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Semantic Meaning");
			this.hbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.semInfo = new global::Gtk.Label();
			this.semInfo.Name = "semInfo";
			this.hbox1.Add(this.semInfo);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.semInfo]));
			w3.Position = 1;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
